language: generic
sudo: required
services:
    - docker
    
deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-1"
    app:    "docker-java"
    env:    "DockerJava-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-052113069199"
    bucket_path: "docker-java"
    access_key_id:
        secure: "AIDAQYIROKSHX6AJ2NZVT"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
    
    